### ISSUE TITLE
Issue with log middleware in client

### ISSUE THREAD

**Issue by zeggel** [cardpay/php-sdk-v3#1]
Hello.
I have issue when I add log middleware to client. I add sample test in my fork to illustrate this problem (you can see it by next link https://github.com/zeggel/php-sdk-v3/commit/d0d141625ff21826ca11b3bb7e618de2490208ed). When I run test I get fail:
![изображение](https://user-images.githubusercontent.com/2827597/62698045-d7759480-b9e4-11e9-9232-a90bd690303d.png)

As mentioned in psr-7 StreamInterface (https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L137), method getContents returns the remaining contents in a string.
I think, when I use log middleware, cursor in the Stream moved to the end and when getContents invoked in sdk it returns empty string.
To avoid this behavior need to invoke rewind() method before getContents or use method __toString or simple cast stream to string, because __toStream method returns whole contents (https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L15)

I added code to PaymentsApi class as example of possible solution (https://github.com/zeggel/php-sdk-v3/commit/7c3ffa3bfd79b56d2d0fde069b17f6c2e876aed2#diff-09fe92ed34ce33c4605ffa5ef23e92d9R127), when I uncomment this code my test pass.
![изображение](https://user-images.githubusercontent.com/2827597/62698928-fecd6100-b9e6-11e9-9254-7156c56cab5d.png)

**Comment by kashukov** [comment]
Hello,
Thank you for the feedback, code was updated accordingly.
Please try to execute test one more time.

**Comment by zeggel** [comment]
Hello. It works fine now. Thank you.
